# permissions for end users to edit demokinds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demokind-editor-role
rules:
- apiGroups:
  - demo.my.domain
  resources:
  - demokinds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.my.domain
  resources:
  - demokinds/status
  verbs:
  - get
