# permissions for end users to view demokinds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demokind-viewer-role
rules:
- apiGroups:
  - demo.my.domain
  resources:
  - demokinds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.my.domain
  resources:
  - demokinds/status
  verbs:
  - get
